[Feat] User Update API
KU-Solution-Challenge-Allergists/GoGreen-Server pull request #47
Opened 2023-03-12 08:06 UTC by KY00KIM

## Type
PR 종류를 확인해 주세요.
- [ ] Improvement
- [X] New feature
- [ ] Bug fix
- [ ] CI/CD, INFRA
- [ ] Etc

## Purpose
User 정보 수정 API

## Why
User 정보 수정 API

## Related issue
Resolve #36

## Additional context
사용자 관련 API를 Auth 모듈에서 다루기 보다 User Module에서 다루는 것이 적합하다 판단되어, User Module 생성하여 진행했습니다.

## Checklist
.

2023-03-12 08:45 UTC, worjs requested changes
고생하셨습니다.
이 내용은 User 모듈을 생성해서 진행하는게 저도 맞다고 생각해요.
자세한 내용은 코멘트 확인해주세요!

2023-03-12 08:45 UTC, worjs commented on src/user/user.repository.ts
> +    return user;
이 쿼리의 리턴타입은 `User`이고, 함수의 반환 타입은 `UserData`입니다.
타입에러가 안뜬 이유는 `User`의 필드가 `UserData`의 필드를 모두 포함하고 있기 때문인데요,
이러한 방식의 타입 체킹을 Duck Typing이라고 하고, 타입스크립트는 이 방식을 채택하고 있습니다.
https://velog.io/@thms200/Typescript-Duck-Typing-%EB%8D%95%ED%83%80%EC%9D%B4%ED%95%91

이렇게 작성하면 런타임에서는 실제로 `UserData`가 아니라, createdAt등 다른 column 정보가 포함된 `User`객체가 나가게 됩니다.

현재 작성된 코드에서는 Dto의 static of 메소드에서 한차례 객체를 새로 생성하였기 때문에, api의 return body에 createdAt과 같은 정보가 포함되지는 않았지만, 저는 코드의 안정성 측면(표기된 타입과 런타임에서의 객체의 타입이 같은)에서 함수 return할때 UserData 포맷으로 객체를 새로 생성하는 쪽을 선호합니다.

2023-03-12 08:45 UTC, worjs commented on src/user/user.service.ts
> +    }
위에서 설명한 이유로, user가 null이 될 가능성이 없으므로 아래의 예외처리는 실행될 일이 없을 것으로 생각됩니다!

2023-03-12 08:45 UTC, worjs commented on src/user/user.repository.ts
> +    });
update쿼리는 잘못된 `userId`의 경우 Error를 냅니다.
즉, update쿼리의 반환 타입은 `User|null` 이 아니라,` User`입니다.

따라서, 적절하게 error를 처리해주거나, 사전에 user의 존재 여부를 확인해주는 처리를 해주시면 되겠습니다.

2023-03-12 08:45 UTC, worjs commented on src/user/user.controller.ts
> +    return this.userService.updateUser(user.id, payload);
url에서 받아온 Path Variable이 아닌 토큰 인증에서 나온 userId가 넘어가고 있네요!

2023-03-12 08:45 UTC, worjs commented on src/user/payload/user.payload.ts
> +    description: '사용자 사진',
`nullable: true` 추가해주세요~

2023-03-12 08:55 UTC, worjs commented
추가로 다른 이슈번호로 브랜치 이름이랑 PR에 resolve tag 된거같아요ㅋㅋ 그거만 수정해주세요!

2023-03-17 15:19 UTC, KY00KIM commented on src/user/user.repository.ts
> +    return user;
그렇네용... 확인했습니다~!

2023-03-17 15:26 UTC, KY00KIM commented on src/user/user.service.ts
> +    }
확인했습니다.

2023-03-17 15:26 UTC, KY00KIM commented on src/user/user.repository.ts
> +    });
확인했습니다.

2023-03-17 15:27 UTC, KY00KIM commented on src/user/user.controller.ts
> +    return this.userService.updateUser(user.id, payload);
앗 그렇네요... api 의미상 당연히 본인만 본인 정보를 수정할거라 생각했는데..

2023-03-17 15:29 UTC, KY00KIM commented on src/user/payload/user.payload.ts
> +    description: '사용자 사진',
확인햇습니당~ 감사함다~

2023-03-18 04:56 UTC, worjs approved these changes
LGTM!

2023-03-18 05:12 UTC, merged